Update didcomm rs dependency
evannetwork/vade-didcomm pull request #14
Opened 2023-06-01 13:28 UTC by vineetpant

## Description
This Mr Updates cargo dependencies to be aligned with updated didcomm-rs for resolving dependency vulnerability issue.

## Detials
- Update didcomm-rs dependency
- Update cargo.toml and cargo.lock files

2023-06-09 12:40 UTC, Tschuck commented on Cargo.toml
> +didcomm-rs = { git = "https://github.com/evannetwork/didcomm-rs.git", branch = "feature/update-dependencies-and-spec-changes", default-features = false }
This will be changed back with new release?

2023-06-16 09:57 UTC, vineetpant commented on Cargo.toml
> +didcomm-rs = { git = "https://github.com/evannetwork/didcomm-rs.git", branch = "feature/update-dependencies-and-spec-changes", default-features = false }
yes , changed

2023-06-16 10:43 UTC, wulfraem requested changes

2023-06-16 10:43 UTC, wulfraem commented on Cargo.toml
> +didcomm-rs = { git = "https://github.com/evannetwork/didcomm-rs.git", cargdefault-features = false }
This looks like a new syntax. :D

```suggestion
didcomm-rs = { git = "https://github.com/evannetwork/didcomm-rs.git", default-features = false }
```

2023-06-16 12:06 UTC, wulfraem approved these changes

2023-06-16 12:07 UTC, Tschuck approved these changes

2023-06-16 12:08 UTC, merged