Add comment field to did-exchange body
evannetwork/vade-didcomm pull request #36
Opened 2023-11-03 09:38 UTC by vineetpant

## Description 

Currently the `DidDocumentBodyAttachment` struct in did-exchange protocol doesn't have `comment` property so it ignores it while parsing

## Details

- Add comment property for did-exchange body
- Update test
- Update versions.md

2023-11-03 12:33 UTC, Tschuck approved these changes

2023-11-07 08:28 UTC, wulfraem requested changes

2023-11-07 08:28 UTC, wulfraem commented on src/protocols/did_exchange/helper.rs
> +                },
We could also use the Rust version of `flatmap` here. ^^

```suggestion
                comment: message
                    .base_message
                    .body
                    .get("comment")
                    .and_then(|label| label.as_str().map(|v| v.to_string())),
```

Basically works like a usual flatmap, even if the name is a bit obscure. It kind of makes sense if you look at the other functions in that context (`and`, `or`, `or_else`) but that naming is a bit... >.>

2023-11-07 12:41 UTC, wulfraem approved these changes

2023-11-07 12:41 UTC, merged